import { Router } from "express";
import { shorten, listUrls, deleteUrl, redirectUrl } from "../controllers/url.controller.js";
import { requireAuth } from "../middleware/auth.middleware.js";
import { validateBody } from "../middleware/validation.middleware.js";
import { shortenSchema } from "../schemas/url.schema.js";
import { rateLimiter } from "../middleware/rateLimiter.js";

const router = Router();
router.post("/shorten", rateLimiter(10, 60), validateBody(shortenSchema), shorten);  
router.get("/urls", requireAuth, listUrls);     //all urls generated by a user
router.delete("/urls/:id", requireAuth, deleteUrl);   
router.get("/:code", redirectUrl);    //redirect to the original url

export default router;
